name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby_version: ['3.0', '3.1', '3.2', '3.3', '3.4']
        rails_version: ['7.1', '7.2', '8.0', '8.1']
        exclude:
          - ruby_version: '3.0'
            rails_version: '7.2'
          - ruby_version: '3.0'
            rails_version: '8.0'
          - ruby_version: '3.1'
            rails_version: '8.0'
          - ruby_version: '3.0'
            rails_version: '8.1'
          - ruby_version: '3.1'
            rails_version: '8.1'
    runs-on: ubuntu-latest
    env:
      RAILS_VERSION: ${{ matrix.rails_version }}
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby_version }}
        bundler-cache: true
    - name: Run the default task
      run: |
        bundle exec rake
